### ISSUE TITLE
项目不能运行

### ISSUE THREAD

**Issue by Android-pengbo** [dengyuhan/android-gpuimage-support#1]
我用GPUimage 和recycleview 使用  滑动后是黑色的 看到你这个解决了  能不能留个联系方式

**Comment by xiandanin** [comment]
试一下setFilter时每次都new一个新的Filter，参考[GPUImageCoverUtil.asyncBindFilterCover](https://github.com/dengyuhan/android-gpuimage-support/blob/master/app/src/main/java/com/dyhdyh/gpuimage/support/example/util/GPUImageCoverUtil.java)

**Comment by xiandanin** [comment]
把工程里的gradle版本，改成你自己的版本重新编译；
如果要示例里用到的库同步不下来，就翻墙再同步

**Comment by Android-pengbo** [comment]
好像是NDK路径不一样
